"""Deterministic synthetic map world generator.

Geometry/trajectories are generated by code. LLM is only used (optionally) to
enrich metadata such as Vietnamese vehicle aliases and scenario descriptions.
"""

from __future__ import annotations

import json
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

from src.world_generator.geometry_utils import (
    DEFAULT_BBOX,
    random_point,
    random_rectangle,
    random_road_segment,
)
from src.world_generator.trajectory_utils import TZ_VN, generate_trajectory

# Pre-built alias pools (no LLM needed for MVP)
_VEHICLE_PREFIXES = ["Truck", "Car", "Bus", "Van", "Motorbike"]
_VI_VEHICLE_PREFIXES = ["Xe tải", "Ô tô", "Xe buýt", "Xe van", "Xe máy"]
_PLATE_PREFIXES = ["51A", "51B", "51C", "51D", "51F", "30A", "30B", "29A", "43A"]


def _make_plate(idx: int, rng: random.Random) -> str:
    prefix = rng.choice(_PLATE_PREFIXES)
    return f"{prefix}-{idx:03d}.{rng.randint(10, 99)}"


def generate_world(
    scenario_id: str,
    *,
    num_vehicles: int = 10,
    num_cameras: int = 5,
    num_zones: int = 3,
    num_roads: int = 3,
    bbox: dict | None = None,
    trajectory_duration_min: int = 30,
    seed: int | None = None,
    base_time: datetime | None = None,
) -> dict:
    """Generate a single synthetic map world as a JSON-serialisable dict."""
    rng = random.Random(seed)
    bbox = bbox or DEFAULT_BBOX
    if base_time is None:
        base_time = datetime(2026, 5, 18, 9, 15, 0, tzinfo=TZ_VN)

    vehicles = []
    time_series: dict[str, dict] = {}

    for i in range(1, num_vehicles + 1):
        vid = f"vehicle_{i:03d}"
        lon, lat = random_point(bbox, rng)
        name_en = f"{rng.choice(_VEHICLE_PREFIXES)} {i:03d}"
        name_vi = f"{rng.choice(_VI_VEHICLE_PREFIXES)} {i:03d}"
        plate = _make_plate(i, rng)
        speed = round(rng.uniform(20, 80), 1)
        heading = round(rng.uniform(0, 360), 1)

        vehicles.append({
            "id": vid,
            "type": "vehicle",
            "name": name_en,
            "aliases": [name_vi, plate, f"xe {i:03d}"],
            "geometry": {"type": "Point", "coordinates": [lon, lat]},
            "properties": {
                "speed_kmh": speed,
                "status": rng.choice(["moving", "stopped", "idle"]),
                "heading_deg": heading,
            },
        })

        traj = generate_trajectory(
            lon,
            lat,
            heading_deg=heading,
            speed_kmh_range=(max(speed - 10, 10), speed + 10),
            duration_minutes=trajectory_duration_min,
            base_time=base_time,
            rng=rng,
        )
        time_series[vid] = {"trajectory": traj}

    cameras = []
    for i in range(1, num_cameras + 1):
        cid = f"camera_{i:02d}"
        lon, lat = random_point(bbox, rng)
        cameras.append({
            "id": cid,
            "type": "camera",
            "name": f"Camera {i:02d}",
            "aliases": [f"cam {i:02d}", f"camera số {i}"],
            "geometry": {"type": "Point", "coordinates": [lon, lat]},
            "properties": {},
        })

    polygons = []
    for i in range(1, num_zones + 1):
        pid = f"zone_{i:02d}"
        center = random_point(bbox, rng)
        w = rng.uniform(300, 800)
        h = rng.uniform(300, 800)
        ring = random_rectangle(center, width_m=w, height_m=h, rng=rng)
        polygons.append({
            "id": pid,
            "type": "polygon",
            "name": f"Zone {i:02d}",
            "aliases": [f"vùng {i:02d}", f"khu vực {i}"],
            "geometry": {"type": "Polygon", "coordinates": [ring]},
            "properties": {},
        })

    lines = []
    for i in range(1, num_roads + 1):
        lid = f"road_{i:02d}"
        coords = random_road_segment(bbox, length_m=rng.uniform(500, 1500), rng=rng)
        lines.append({
            "id": lid,
            "type": "line",
            "name": f"Road {i:02d}",
            "aliases": [f"đường {i:02d}", f"tuyến {i}"],
            "geometry": {"type": "LineString", "coordinates": coords},
            "properties": {},
        })

    return {
        "scenario_id": scenario_id,
        "coordinate_system": "EPSG:4326",
        "time": base_time.isoformat(),
        "objects": {
            "vehicles": vehicles,
            "cameras": cameras,
            "polygons": polygons,
            "lines": lines,
        },
        "time_series": time_series,
    }


def generate_worlds(
    count: int = 100,
    *,
    output_dir: str | Path = "scenarios",
    base_seed: int = 42,
    small_fraction: float = 0.3,
    medium_fraction: float = 0.5,
) -> list[Path]:
    """Generate *count* worlds and write them as JSON to *output_dir*.

    Returns the list of written file paths.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []

    for i in range(1, count + 1):
        sid = f"traffic_synthetic_{i:03d}"
        r = i / count
        if r <= small_fraction:
            cfg = dict(num_vehicles=5, num_cameras=3, num_zones=2, num_roads=2)
        elif r <= small_fraction + medium_fraction:
            cfg = dict(num_vehicles=20, num_cameras=10, num_zones=5, num_roads=5)
        else:
            cfg = dict(num_vehicles=50, num_cameras=20, num_zones=10, num_roads=8)

        world = generate_world(sid, seed=base_seed + i, **cfg)
        p = out / f"{sid}.json"
        p.write_text(json.dumps(world, indent=2, ensure_ascii=False), encoding="utf-8")
        paths.append(p)

    return paths
